version: '3'

services:
    mysql-admin:
        image:                   phpmyadmin/phpmyadmin
        environment: 
            PMA_HOST:            mysql-server
            PMA_PORT:            3306
            MYSQL_ROOT_PASSWORD: userpass
        networks:
            -                    app-fullstack-net
        depends_on:
            -                    mysql-server
        ports:
            -                    "8001:80"

    node-backend:
        image:                   abassi/nodejs-server:10.0-dev
        volumes:
            -                    ./src/backend:/home/node/app/src
            -                    ./src/frontend:/home/node/app/static
        networks:
            -                    app-fullstack-net
        depends_on:
            -                    mysql-server
        ports: 
            -                    "8000:3000"
        command:                 nodemon /home/node/app/src/index.js

networks:
    app-fullstack-net:
        driver:                  bridge